import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { useTranslation } from "react-i18next";
const About = () => {
    const { t } = useTranslation();
    const cascadeVariant = {
        hidden: { opacity: 0, y: 20 },
        visible: (i = 0) => ({
            opacity: 1,
            y: 0,
            transition: { delay: i * 0.3, duration: 1, ease: "easeOut" },
        }),
    };
    return (_jsx("section", { id: "about", className: "min-h-screen bg-gray-900 text-white px-8 py-16", children: _jsxs("div", { className: "max-w-6xl mx-auto space-y-12", children: [_jsxs(motion.div, { initial: { opacity: 0, y: -20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 1 }, className: "text-center space-y-4", children: [_jsx("h2", { className: "text-4xl sm:text-4xl font-extrabold text-transparent bg-clip-text \r\n       bg-gradient-to-r from-green-600 via-green-400 to-white", children: t("about.title") }), _jsx("div", { className: "flex justify-center px-2 sm:px-4", children: _jsxs("p", { className: "\r\n      text-lg\r\n      sm:text-xl\r\n      text-gray-300\r\n      italic\r\n      leading-relaxed\r\n      text-center\r\n      inline-flex\r\n      items-start\r\n      justify-center\r\n      max-w-3xl\r\n    ", children: [_jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "\r\n        flex-shrink-0\r\n        w-5\r\n        h-5\r\n        sm:w-6\r\n        sm:h-6\r\n       -mr-2\r\n        sm:mr-2\r\n        -translate-y-1\r\n        animate-quoteColor\r\n      ", fill: "currentColor", viewBox: "0 0 24 24", "aria-hidden": "true", children: _jsx("path", { d: "M7 17h3l2-7V5H6v5h3l-2 7zm7 0h3l2-7V5h-6v5h3l-2 7z" }) }), _jsx("span", { children: t("about.subtitle") }), _jsx("svg", { xmlns: "http://www.w3.org/2000/svg", className: "\r\n        flex-shrink-0\r\n        w-5\r\n        h-5\r\n        sm:w-6\r\n        sm:h-6\r\n        -ml-3\r\n        sm:ml-2\r\n        translate-y-1\r\n        rotate-180\r\n        animate-quoteColor\r\n      ", fill: "currentColor", viewBox: "0 0 24 24", "aria-hidden": "true", children: _jsx("path", { d: "M7 17h3l2-7V5H6v5h3l-2 7zm7 0h3l2-7V5h-6v5h3l-2 7z" }) })] }) })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-12 items-center mb-6", children: [_jsxs("div", { className: "relative w-full h-auto", children: [_jsx(motion.img, { src: "/images/about.jpg", alt: t("about.mainImageAlt"), className: "\r\n      w-68 h-80 sm:w-80 sm:h-80 md:w-110 md:h-110\r\n      object-cover rounded-xl shadow-lg \r\n      mt-6 sm:mt-10 md:mt-15 \r\n      translate-x-0 sm:translate-x-0 md:-translate-x-12\r\n    ", initial: { opacity: 0 }, whileInView: { opacity: 1 }, transition: { duration: 1, ease: "easeOut" }, animate: {
                                        boxShadow: [
                                            "0 0 15px rgba(255,165,0,0.8)",
                                            "0 0 25px rgba(255,255,255,0.6)",
                                            "0 0 15px rgba(255,165,0,0.8)",
                                        ],
                                    } }), _jsx(motion.img, { src: "/images/hero8.jpg", alt: t("about.secondaryPhotoAlt"), className: "\r\n      absolute top-4 right-4 \r\n      w-24 h-25 sm:w-32 sm:h-28 md:w-40 md:h-35\r\n      object-cover rounded-lg shadow-xl ring-4 ring-white\r\n      -translate-x-3 sm:translate-x-4 md:translate-x-0\r\n      translate-y-0 sm:translate-y-2 md:translate-y-0\r\n    ", initial: { opacity: 0, x: 50, y: -20 }, whileInView: { opacity: 1, x: 0, y: 0 }, transition: { duration: 1, delay: 0.3 } }), _jsx(motion.video, { src: "/videos/about1.mp4", autoPlay: true, loop: true, muted: true, playsInline: true, className: "\r\n    absolute bottom-4 right-4 \r\n    w-28 h-30 sm:w-40 sm:h-50 md:w-50 md:h-60\r\n    object-cover rounded-lg shadow-xl ring-4 ring-white \r\n    translate-y-0 sm:translate-y-6 md:translate-y-15 \r\n    translate-x-0 sm:translate-x-4 md:translate-x-5\r\n  ", initial: { opacity: 0, x: 50, y: 20 }, whileInView: { opacity: 1, x: 0, y: 0 }, transition: { duration: 1, delay: 0.6 } })] }), _jsxs(motion.div, { variants: cascadeVariant, initial: "hidden", whileInView: "visible", viewport: { once: true, amount: 0.4 }, className: "space-y-6 text-justify", children: [_jsx("p", { className: "text-gray-300 leading-relaxed", children: t("about.paragraph1") }), _jsx("p", { className: "text-gray-300 leading-relaxed", children: t("about.paragraph2") }), _jsxs("ul", { className: "list-disc list-inside text-gray-300 space-y-2", children: [_jsx("li", { children: t("about.list.item1") }), _jsx("li", { children: t("about.list.item2") }), _jsx("li", { children: t("about.list.item3") }), _jsx("li", { children: t("about.list.item4") })] }), _jsxs("div", { className: "flex gap-4 mt-6", children: [_jsx("a", { href: "/projects", className: "px-6 py-3 bg-orange-600 text-white font-bold rounded-lg shadow-lg hover:bg-orange-700 transition", children: t("about.buttonPortfolio") }), _jsx("a", { href: t("about.buttonBookingLink"), target: "_blank", rel: "noopener noreferrer", className: "px-6 py-3 bg-green-600 text-white font-bold rounded-lg shadow-lg hover:bg-green-700 transition", children: t("about.buttonBooking") })] })] })] })] }) }));
};
export default About;
